"""initial

Revision ID: 3817d8d5448b
Revises: 
Create Date: 2026-04-30 05:58:33.812751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3817d8d5448b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_country', sa.String(length=100), nullable=False),
    sa.Column('destination_country', sa.String(length=100), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=True),
    sa.Column('requires_kyc', sa.Boolean(), nullable=True),
    sa.Column('requires_travel_rule', sa.Boolean(), nullable=True),
    sa.Column('reporting_threshold', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('kyc_expiry_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'treasury_officer', 'compliance_officer', 'auditor', 'reviewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('ai_preference', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('payment_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_company', sa.String(length=255), nullable=False),
    sa.Column('receiver_company', sa.String(length=255), nullable=False),
    sa.Column('source_country', sa.String(length=100), nullable=False),
    sa.Column('destination_country', sa.String(length=100), nullable=False),
    sa.Column('source_chain', sa.String(length=100), nullable=False),
    sa.Column('destination_chain', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('token', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('sender_wallet', sa.String(length=42), nullable=True),
    sa.Column('receiver_wallet', sa.String(length=42), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('intent_hash', sa.String(length=64), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revert_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'under_review', 'approved', 'rejected', 'executed', 'failed', 'blocked', 'revalidation', name='paymentstatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_intents_intent_hash'), 'payment_intents', ['intent_hash'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('approved', 'blocked', 'review_needed', 'revalidation_triggered', 'settlement_executed', 'settlement_failed', name='alerttype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('approve', 'reject', 'escalate', name='approvalaction'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_intents.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('country_policy_result', sa.JSON(), nullable=True),
    sa.Column('wallet_risk_result', sa.JSON(), nullable=True),
    sa.Column('issuer_risk_result', sa.JSON(), nullable=True),
    sa.Column('chain_governance_result', sa.JSON(), nullable=True),
    sa.Column('liquidity_result', sa.JSON(), nullable=True),
    sa.Column('ai_decision', sa.Enum('direct_transfer', 'alternate_chain', 'alternate_token', 'delay_transfer', 'split_payment', 'manual_review', 'block', name='aidecisiontype'), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.String(length=50), nullable=True),
    sa.Column('ai_flags', sa.JSON(), nullable=True),
    sa.Column('ai_alternatives', sa.JSON(), nullable=True),
    sa.Column('ai_engine_used', sa.String(length=50), nullable=True),
    sa.Column('ai_prompt_tokens', sa.String(length=50), nullable=True),
    sa.Column('ai_latency_ms', sa.String(length=50), nullable=True),
    sa.Column('ai_risk_summary', sa.Text(), nullable=True),
    sa.Column('fhe_check_result', sa.JSON(), nullable=True),
    sa.Column('zk_proof_reference', sa.Text(), nullable=True),
    sa.Column('policy_version', sa.String(length=255), nullable=True),
    sa.Column('final_decision', sa.Enum('approved', 'rejected', 'blocked', 'pending_review', name='finaldecision'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revalidation_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=False),
    sa.Column('original_decision', sa.String(length=50), nullable=False),
    sa.Column('new_risk_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_decision', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', name='revalidationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('on_chain_proof_hash', sa.String(length=66), nullable=True),
    sa.Column('report_path', sa.Text(), nullable=True),
    sa.Column('zk_proof_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['compliance_decisions.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_records')
    op.drop_table('revalidation_records')
    op.drop_table('compliance_decisions')
    op.drop_table('approvals')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_payment_intents_intent_hash'), table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('policy_rules')
    # ### end Alembic commands ###
